name: Formatting

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  checkFormat:
    runs-on: ubuntu-latest
    steps:
     - name: autopep8
       id: autopep8
       uses: peter-evans/autopep8@v2
       with:
         args: --recursive --diff --exit-code .
     - name: Fail if autopep8 made changes
       if: steps.autopep8.outputs.exit-code == 2
       run: exit 1
